describe('executable', function () {
    this.timeout(10000)
    const assert = require('assert')
    process.on('unhandledRejection', error => { throw error })
    it('can execute', async () => {
        const prolific = require('..')
        const path = require('path')
        const stream = require('stream')
        const program = path.join(__dirname, 'program.js')
        const processor = path.join(__dirname, 'prolific.bin.prolific.js')
        const child = prolific([ '--inherit', '99', '--processor', processor, 'node', program ])
        await new Promise(resolve => setTimeout(resolve, 1000))
        child.destroy()
        assert.equal(0, await child.promise, 'ran')
    })
})
