language: node_js

node_js:
  - '12'
  - '14'
  - '15'

branches:
  only:
    - master
    - travis-ci

install:
  - npm install --no-package-lock --no-save
  - npm install -g nyc prove

script:
  - nyc bash -c 'for dir in prolific.*; do (cd $dir && [ ! -e package.json ] && true || { [ ! -e skip ] && npm test; }) || exit 1; done'
