sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: "DnSHK4cW0eAnB7m12pHrpsZK0t1X8dlVr5AwmX9Due3nsxfZXYct2ZRBbAy+KT2PmHw+bhN+4NvVQuDg9MRz9tPPv1AkQYlRvqSGf1jFgYbCF9DdRYO0tgm58jS3CsDJ0Dn2aZCa33Q1GbJsrAgE3v79gVss6mX9JykcYxu75v7aofSDgcSKO7jT00aCeQtBxNg/NxD9jR4rDEEkLlwrScv9gbMdbrn575hVQGVoKLT/Yx1Nkv2CISNhAOm5ZxDSi0uIiZ5DvSyorPxuEA0unWsKSZKGj4a2+8deG7Fsact4ntdOYJk7aFfBnN7chjaSiV1cGM2/mXX/7QQ2R8aZIClK9gfGM+7z1+XEQYQuXFkNbPNK36Ru81DjcfFraXCL+pWGNIhoFD6UCo97zpyL5mtF1U1BIGwkH0qYkMjEJrn1NMXmT+bd1XStVBYHigiHEknGNaQkNca5WxthWRzzCdom2Ip1HXLWiWFuMYjthZXoSfFSWzPptgXtcfwNfBRonlNJgyOPu8zzpeaFSLXPgYQ8MYS6+HuCEfqBmear0tsVyzqBK5jBKV44DWiF6TJqbhIsWKaUwaht6HN/x1goS9Aobq1INMAGJBGvQf6qNkpGu2G0scW2jLw1xBnKhDl+BSF4kaKShAfXSj8WctVrtFCihp+l7MdifuwRp0vj+KE="
