sudo: false

language: node_js

node_js:
  - '12'

branches:
  only:
    - master
    - travis-ci

install:
  - for dir in prolific.*; do (cd $dir && npm install --no-save --no-package-lock); done
  - npm install --no-save --no-package-lock
  - npm install -g nyc mocha
  - git checkout .

script:
  - for dir in prolific.*; do
      if [[ -n "$(find $dir/test -maxdepth 1 -name \*.test.js -print -quit)" ]]; then
        (cd $dir && nyc npm test) || exit 1
      fi
    done
