sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'

branches:
  only:
    - master
    - travis-ci

before_install:
  - for dir in prolific.*; do (cd $dir && npm install); done
  - git checkout .
  - npm install --no-shrinkwrap
  - npm install --no-shrinkwrap istanbul coveralls
