sudo: false

language: node_js

node_js:
  - '4'
  - '6'
  - '8'
  - '10'

branches:
  only:
    - master
    - travis-ci

install:
  - for dir in prolific.*; do (cd $dir && npm install --no-save --no-package-lock); done
  - npm install --no-save --no-package-lock
  - npm install -g istanbul coveralls
  - git checkout .
