language: node_js

node_js:
  - '12'
  - '14'
  - '15'

branches:
  only:
    - master
    - travis-ci

install:
  - for dir in prolific.*; do (cd $dir && [[ -e package.json && ! -e skip ]] && npm install --no-save --no-package-lock || true); done && git checkout .
  - npm install -g nyc prove

script:
  - nyc bash -c 'for dir in prolific.*; do (cd $dir && { [[ ! -e package.json && -e skip ]] && true; } || npm test) || exit 1; done'
