var logger = require('prolific.logger').createLogger('bigeasy.prolific.test')
var shuttle = require('prolific.shuttle').shuttle(process, 100, logger)
process.stderr.write(JSON.stringify(process.env) + '\n')
logger.info('hello', {})
setTimeout(function () { shuttle.stop() }, 250)
