name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: for dir in prolific.executable; do (cd $dir && npm install --no-save --no-package-lock); done
    - name: npm ls
      run: for dir in prolific.executable;; do (cd $dir && npm ls); done
    - name: npm install nyc, mocha, codecov
      run:  npm install -g nyc mocha codecov
    - name: npm test
      run: cd prolific.executable && nyc npm test
      env:
        CI: true
    - name: generate codecov report
      run: cd prolific.executable && nyc report --reporter=text-lcov > coverage.lcov
    - name: ship coverage to codecov
      run: cd prolific.executable && codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
